objects=Application.cpp Application.h GameObject.cpp GameObject.h InputSystem.cpp InputSystem.h main.cpp NoaMath.cpp NoaMath.h Player.cpp Player.h Scene.cpp Scene.h SceneManager.cpp SceneManager.h TestScene.cpp TestScene.h Graphic.h Graphic.cpp

game:$(objects)
	g++ $(objects) -static -o game

clean:
	rm -rf game
